commit/test: skip flaky commit tests
This skips two tests which are randomly flaking with:
```
--- FAIL: TestCommitTreeParentSuccess (0.02s)
commit_test.go:184: failed to commit:
 pkg/otbuiltin/commit.go:407 - Writing content object:
  fchown: Operation not permitted
```